# This is a basic workflow to help you get started with Actions

name: py

# Controls when the action will run. 
on:
  schedule:
    - cron: "* /5 * * * *" #runs cronjob every 5 minutes
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubunto-latest
    steps:
      -name: checkout repo content
       uses: actions/checkout@v2
      -name: setup python
       uses: actions/setup-python@v2
       with:
        python-version: 3.8
      -name: execute py script
       run: |
         python issue_generator.py
       env:
        git_token: ${{GH_TOKEN.key}}
        
        
        
