# This is a basic workflow to help you get started with Actions

name: update_issues

# Controls when the action will run. 
on:
  #schedule:
  #  - cron: "* * * * *" #runs cronjob every 5 minutes
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest #tst
    steps:
      - uses: actions/checkout@v2.1.0
      - run:
          python -m pip install --upgrade pip
      - run:
          pip install PyGithub
      - run:
          python issue_generator.py
        env:
          git_token: ${{secrets.GH_TOKEN}}
